#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mariadb://rds??:???(??? 3306)/database?
#spring.datasource.username=db??
#spring.datasource.password=db??????
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 1. request attribute? ??? model? ????.
#spring.mustache.servlet.expose-request-attributes=true
# 2. session attribute? ??? model? ????.
#spring.mustache.servlet.expose-session-attributes=true

#서버
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # JPA 기본설정
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true # paging 0부터 index 1로 변경


  # 세션 프론트에서 노출 허용
  mustache:
    servlet:
      expose-session-attributes: true
    expose-session-attributes: true