#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mariadb://rds??:???(??? 3306)/database?
#spring.datasource.username=db??
#spring.datasource.password=db??????
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 1. request attribute? ??? model? ????.
#spring.mustache.servlet.expose-request-attributes=true
# 2. session attribute? ??? model? ????.
#spring.mustache.servlet.expose-session-attributes=true

#서버
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# 쿠키 허용
    session:
      cookie:
        secure: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # JPA 기본설정
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true # paging 0부터 index 1로 변경
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


  # 세션 프론트에서 노출 허용
  #  - principal.username: { [ SPRING_SECURITY_CONTEXT.Authentication.Principal.username ] }
  #  - accessToken: { [ accessToken ] }
  #  - refresjToken: { [ refreshToken ] }
  mustache:
    servlet:
      expose-session-attributes: true
  
# 파일관련 설정
# spring:
  servlet.multipart.maxFileSize: 10MB
  servlet.multipart.maxRequestSize: 50MB


# 리소스 캐시 설정
  web:
    resources:
      cache:
        period: 86400 #1일